# Autogenerated by devscripts/update-version.py

__version__ = '2025.07.21.042057'

RELEASE_GIT_HEAD = '3b1d34fb99a90dcb96fcd9f256819bc5eb657a68'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'snehilrx/yt-dlp-dev'

ORIGIN = 'snehilrx/yt-dlp-dev'

_pkg_version = '2025.07.21.042057'
